"""
The vocal layers that make a take sound produced.

A lead vocal alone over a beat reads as a demo however well it is mixed.
What a record adds is layers: doubles that thicken the hook, an octave
underneath, a harmony on the last line, ad-libs answering in the gaps. The
engine can generate all of these from the single take it has, and this is
where the biggest audible difference between "a mix" and "a song" lives.

The thing that makes a synthetic double work -- or fail completely -- is
that **it must differ in time and pitch, and differ continuously**. A
delayed copy of a signal is not a double, it is a comb filter: every
frequency whose period divides the delay cancels, and the result is a
hollow, phasey lead rather than a thicker one. A real double is a second
performance, so it drifts a few tens of milliseconds around the lead and
sits a few cents off it, and both wander across the phrase.

So doubles here are generated by warping the lead along a slow random walk
and detuning it slightly, reusing the same variable-rate machinery the
alignment stage uses. The walk is seeded per layer, which keeps renders
reproducible -- an unreproducible mix cannot be debugged.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Callable, Dict, List, Optional, Sequence, Tuple

import numpy as np

from ..align import warp as warp_mod
from ..audio import dsp

log = logging.getLogger("mixengine.arrange.layers")

# Timing and tuning spread for a generated double, in ms and cents. These
# are the measured range of real double-tracking, not free parameters: much
# less and the comb filtering returns, much more and it reads as two
# different singers rather than one singer twice.
DOUBLE_TIME_SPREAD_MS = 22.0
DOUBLE_DETUNE_CENTS = 11.0
WIDE_TIME_SPREAD_MS = 34.0
WIDE_DETUNE_CENTS = 16.0

# How often the walk changes direction. Around a second: fast enough to be
# a performance, slow enough not to be vibrato.
WALK_PERIOD_S = 0.9


@dataclass
class Layer:
    name: str
    audio: np.ndarray
    gain_db: float = -8.0
    pan: float = 0.0
    regions: List[Tuple[int, int]] = field(default_factory=list)
    note: str = ""

    def to_dict(self) -> dict:
        return {"name": self.name, "gain_db": round(self.gain_db, 2),
                "pan": round(self.pan, 3), "regions": len(self.regions),
                "note": self.note}


def build(vocal: np.ndarray, sr: int, *,
          wanted: Dict[str, List[Tuple[int, int]]],
          tessitura: Optional[Tuple[float, float]] = None,
          seed: int = 0,
          notes: Optional[Sequence] = None,
          chord_at: Optional[Callable[[float], object]] = None,
          key_at: Optional[Callable[[float], object]] = None
          ) -> Tuple[List[Layer], dict]:
    """Generate every requested layer over the regions it applies to.

    `wanted` maps a layer name to the sample regions it should cover, which
    the arranger derives from the energy contour: doubles on hooks, harmony
    only where the energy is highest, ad-libs in the gaps. A layer with no
    regions is not generated at all rather than generated and muted, since
    the generation is the expensive part.

    `notes`, `chord_at` and `key_at` make the harmony chord-aware. Without
    them it falls back to a diatonic third and says so in its note.
    """
    v = dsp.as_2d(vocal)
    out: List[Layer] = []
    report: Dict = {"requested": sorted(wanted.keys()), "built": [],
                    "skipped": {}}

    builders = {
        "tight_double": lambda r: _double(
            v, sr, r, DOUBLE_TIME_SPREAD_MS, DOUBLE_DETUNE_CENTS,
            gain_db=-9.0, pan=0.0, seed=seed + 1, name="tight_double"),
        "wide_double": lambda r: _wide_pair(
            v, sr, r, seed=seed + 2),
        "octave_down": lambda r: _octave(v, sr, r, -12.0, gain_db=-16.0,
                                         seed=seed + 4),
        "harmony": lambda r: _harmony(v, sr, r, tessitura, seed=seed + 5,
                                      notes=notes, chord_at=chord_at,
                                      key_at=key_at),
        "adlibs": lambda r: _adlibs(v, sr, r, seed=seed + 6),
        "whisper_layer": lambda r: _whisper(v, sr, r, seed=seed + 7),
    }

    for name, regions in wanted.items():
        fn = builders.get(name)
        if fn is None:
            report["skipped"][name] = "no builder"
            continue
        if not regions:
            report["skipped"][name] = "no regions"
            continue
        try:
            made = fn(regions)
        except Exception as exc:
            log.warning("layer %s failed: %s", name, exc)
            report["skipped"][name] = f"failed: {exc}"
            continue
        for layer in (made if isinstance(made, list) else [made]):
            if layer is None:
                continue
            out.append(layer)
            report["built"].append(layer.to_dict())
    return out, report


# ─────────────────────────────────────────────────────────────────────────────

def _mask(v: np.ndarray, regions: Sequence[Tuple[int, int]],
          sr: int = 44100) -> np.ndarray:
    """The lead, silent outside `regions`, with short fades at each edge."""
    out = np.zeros_like(v)
    fade = max(8, int(0.008 * sr))
    for s, e in regions:
        s, e = int(max(0, s)), int(min(len(v), e))
        if e - s < fade * 2:
            continue
        out[s:e] = v[s:e]
        t = np.linspace(0.0, 1.0, fade, dtype=np.float32)[:, None]
        out[s:s + fade] *= t
        out[e - fade:e] *= (1.0 - t)
    return out


def _walk(n_anchors: int, spread_ms: float, seed: int) -> np.ndarray:
    """A smooth, zero-mean random walk in seconds, bounded by `spread_ms`.

    Bounded rather than free: an unbounded walk drifts away from the lead
    and stops being a double. Smoothed because a walk that steps every
    anchor is jitter, and jitter on a vocal is a flanger.
    """
    rng = np.random.default_rng(seed)
    steps = rng.normal(0.0, 1.0, max(n_anchors, 2))
    k = max(2, n_anchors // 8)
    kern = np.ones(k) / k
    smooth = np.convolve(steps, kern, mode="same")
    peak = float(np.max(np.abs(smooth))) or 1.0
    return (smooth / peak) * (spread_ms / 1000.0)


def _time_vary(v: np.ndarray, sr: int, spread_ms: float,
               seed: int) -> np.ndarray:
    """Warp along a slow random walk: the take, performed slightly differently."""
    dur = len(v) / float(sr)
    if dur < 1.0:
        return v
    n = max(3, int(dur / WALK_PERIOD_S))
    src = np.linspace(0.0, dur, n)
    offs = _walk(n, spread_ms, seed)
    offs[0] = offs[-1] = 0.0            # keep start and end coincident
    out, _ = warp_mod.warp(v, sr, src, src + offs, preserve_formants=True)
    return dsp.pad_to(out, len(v))[:len(v)]


def _detune(v: np.ndarray, sr: int, cents: float) -> np.ndarray:
    from ..audio.transform import pitch_shift
    if abs(cents) < 0.5:
        return v
    return dsp.pad_to(pitch_shift(v, sr, cents / 100.0,
                                  preserve_formants=True), len(v))[:len(v)]


def _double(v: np.ndarray, sr: int, regions, spread_ms: float, cents: float,
            *, gain_db: float, pan: float, seed: int, name: str) -> Layer:
    src = _mask(v, regions, sr)
    out = _time_vary(src, sr, spread_ms, seed)
    rng = np.random.default_rng(seed)
    out = _detune(out, sr, float(rng.uniform(-cents, cents)))
    # Doubles support the lead rather than competing with it, so the
    # fundamental is left to the lead and only the body and air are doubled.
    out = dsp.highpass(out, sr, 180.0, order=2)
    # No panning here. `sum_layers` pans every layer that carries a pan
    # value, and doing it in both places applied the constant-power law
    # twice -- squaring the channel gains, so a 0.72 pan rendered as 0.95
    # and the layer lost level on its louder side.
    return Layer(name=name, audio=out.astype(np.float32), gain_db=gain_db,
                 pan=pan, regions=list(regions),
                 note=f"{spread_ms:.0f} ms walk, {cents:.0f} cent detune")


def _wide_pair(v: np.ndarray, sr: int, regions, seed: int) -> List[Layer]:
    """Two independently varied doubles, hard left and hard right.

    Independent is the point. The same signal panned to both sides is a
    mono signal; two different performances are what opens the stereo
    image, and it is also why this survives a mono fold-down -- the two
    sides do not cancel because they were never the same waveform.
    """
    left = _double(v, sr, regions, WIDE_TIME_SPREAD_MS, WIDE_DETUNE_CENTS,
                   gain_db=-12.0, pan=-0.72, seed=seed, name="wide_double_l")
    right = _double(v, sr, regions, WIDE_TIME_SPREAD_MS, WIDE_DETUNE_CENTS,
                    gain_db=-12.0, pan=0.72, seed=seed + 101,
                    name="wide_double_r")
    return [left, right]


def _octave(v: np.ndarray, sr: int, regions, semitones: float,
            *, gain_db: float, seed: int) -> Optional[Layer]:
    from ..audio.transform import pitch_shift
    src = _mask(v, regions, sr)
    if float(np.max(np.abs(src))) < 1e-5:
        return None
    # Formants are *not* preserved here: an octave-down layer is supposed
    # to sound like a bigger body behind the lead, and preserving the
    # original formants keeps it sounding like the same voice an octave
    # lower, which reads as an artifact rather than a part.
    out = dsp.pad_to(pitch_shift(src, sr, semitones, preserve_formants=False),
                     len(v))[:len(v)]
    out = dsp.lowpass(out, sr, 2200.0, order=2)
    out = dsp.highpass(out, sr, 70.0, order=2)
    return Layer(name="octave_down", audio=out.astype(np.float32),
                 gain_db=gain_db, regions=list(regions),
                 note="low-passed so it adds weight without doubling diction")


def _harmony(v: np.ndarray, sr: int, regions,
             tessitura: Optional[Tuple[float, float]], seed: int, *,
             notes: Optional[Sequence] = None,
             chord_at: Optional[Callable] = None,
             key_at: Optional[Callable] = None) -> Optional[Layer]:
    """A harmony a third above, inside the chord at every moment.

    A fixed transposition is not a harmony -- shift a melody up four
    semitones and half the notes land outside the chord. A real harmony
    part moves in thirds *of the scale*, so the interval alternates between
    three and four semitones depending on where in the key the note sits,
    and `theory.generate_harmony` computes exactly that per note against
    the chord sounding underneath it.

    The shifting is done by *distinct offset*, not per note: the offsets a
    third produces are almost always 3 or 4 semitones, so the masked source
    is shifted twice and each note's span is taken from the version that
    matches its offset. Shifting seventy notes individually would be
    seventy Rubber Band processes for the same result.

    Offsets are rounded to the nearest semitone. The lead's own detune is
    the singer's expression; shifting by the exact fractional offset would
    land the harmony on the theoretical pitch and make it the one voice in
    the stack that is perfectly in tune, which reads as synthetic.

    Without note events the layer falls back to a fixed diatonic third and
    the note says so. It sits lowest in the mix either way.
    """
    from ..audio.transform import pitch_shift
    from ..musical import theory

    src = _mask(v, regions, sr)
    if float(np.max(np.abs(src))) < 1e-5:
        return None
    n = len(v)

    tess = None
    if tessitura and tessitura[1] > 0 and tessitura[1] > tessitura[0]:
        tess = (float(tessitura[0]), float(tessitura[1]))

    in_region = []
    if notes:
        for nt in notes:
            start = float(getattr(nt, "start", 0.0))
            end = float(getattr(nt, "end", 0.0))
            midi = float(getattr(nt, "midi", 0.0))
            if end <= start or midi <= 0:
                continue
            a, b = int(start * sr), int(end * sr)
            if any(a < re and b > rs for rs, re in regions):
                in_region.append((start, end, midi))

    if in_region and (chord_at is not None or key_at is not None):
        chord_fn = chord_at or (lambda t: None)
        key_fn = key_at or (lambda t: None)
        times = [(s + e) / 2.0 for s, e, _ in in_region]
        voice = theory.generate_harmony(
            [m for _, _, m in in_region], times, chord_fn, key_fn,
            interval="third", direction=1, tessitura=tess)
        offsets = [int(round(o)) for o in voice.offsets]

        shifted: Dict[int, np.ndarray] = {}
        for off in sorted(set(offsets)):
            if off == 0:
                shifted[off] = src
                continue
            shifted[off] = dsp.pad_to(
                pitch_shift(src, sr, float(off), preserve_formants=True), n)[:n]

        out = np.zeros_like(src)
        fade = max(8, int(sr * 0.010))
        for (s, e, _), off in zip(in_region, offsets):
            a, b = max(0, int(s * sr)), min(n, int(e * sr))
            if b - a < fade * 2:
                continue
            seg = shifted[off][a:b].copy()
            ramp = np.linspace(0.0, 1.0, fade, dtype=np.float32)[:, None]
            seg[:fade] *= ramp
            seg[-fade:] *= ramp[::-1]
            out[a:b] += seg
        counts: Dict[int, int] = {}
        for off in offsets:
            counts[off] = counts.get(off, 0) + 1
        note = (f"chord-aware: {len(in_region)} notes, intervals "
                + ", ".join(f"{k:+d}st x{c}" for k, c in sorted(counts.items())))
    else:
        out = dsp.pad_to(pitch_shift(src, sr, 3.0, preserve_formants=True), n)[:n]
        note = "diatonic third (no note events available)"

    out = dsp.highpass(out, sr, 250.0, order=2)
    out = dsp.lowpass(out, sr, 9000.0, order=2)
    return Layer(name="harmony", audio=out.astype(np.float32), gain_db=-17.0,
                 pan=0.35, regions=list(regions), note=note)


def _adlibs(v: np.ndarray, sr: int, regions, seed: int) -> Optional[Layer]:
    """Phrase tails echoed into the gaps after them.

    The material is the singer's own last word, which is what an ad-lib
    usually is, so it needs no new performance and always fits the lyric.
    Placed *after* the phrase rather than under it, because an ad-lib on
    top of the line it answers is just a double.
    """
    if not regions:
        return None
    out = np.zeros_like(v)
    rng = np.random.default_rng(seed)
    placed = 0
    for s, e in regions:
        s, e = int(max(0, s)), int(min(len(v), e))
        tail = min(int(sr * 0.45), max(0, e - s))
        if tail < int(sr * 0.12):
            continue
        src = v[e - tail:e]
        delay = int(sr * float(rng.uniform(0.09, 0.16)))
        pos = e + delay
        if pos + tail > len(v):
            continue
        w = np.hanning(tail)[:, None].astype(np.float32)
        out[pos:pos + tail] += src * w * 0.9
        placed += 1
    if placed == 0:
        return None
    out = dsp.highpass(out, sr, 320.0, order=2)
    out = dsp.lowpass(out, sr, 7000.0, order=2)
    return Layer(name="adlibs", audio=out.astype(np.float32), gain_db=-15.0,
                 pan=-0.45, regions=list(regions),
                 note=f"{placed} tails echoed into the gaps after phrases")


def _whisper(v: np.ndarray, sr: int, regions, seed: int) -> Optional[Layer]:
    """A breathy layer under the loudest moments.

    Built from the lead's own high band, compressed hard and detuned, which
    is close to what a whisper track actually contributes: consonant
    definition and air rather than pitch.
    """
    src = _mask(v, regions, sr)
    if float(np.max(np.abs(src))) < 1e-5:
        return None
    hi = dsp.highpass(src, sr, 3500.0, order=2)
    # `compressor` returns `(audio, mean_gain_reduction_db)`. Ignoring the
    # second element is not optional -- passing the tuple on raised
    # `'tuple' object has no attribute 'astype'`, which the builder loop
    # caught and reported as a skipped layer. The render then shipped
    # without a whisper track and said so only in the layer report.
    hi, _gr = dsp.compressor(hi, sr, threshold_db=-34.0, ratio=6.0,
                             attack_ms=2.0, release_ms=90.0)
    hi = _time_vary(hi, sr, 16.0, seed)
    return Layer(name="whisper_layer", audio=hi.astype(np.float32),
                 gain_db=-22.0, pan=0.25, regions=list(regions),
                 note="air and consonants only")


def sum_layers(layers: Sequence[Layer], n: int, n_ch: int = 2) -> np.ndarray:
    """Mix every layer down to one stereo bus at its own gain and pan."""
    out = np.zeros((n, n_ch), dtype=np.float32)
    for L in layers:
        a = dsp.as_2d(L.audio)
        a = dsp.match_channels(a, n_ch)
        a = dsp.pad_to(a, n)[:n]
        g = dsp.db_to_lin(L.gain_db)
        if abs(L.pan) > 1e-3 and n_ch == 2:
            a = dsp.pan(dsp.to_mono(a)[:, None], L.pan)
            a = dsp.pad_to(dsp.as_2d(a), n)[:n]
        out += a * g
    return out
